/*
 The auto discovered external dependencies may be incorrect for your platform.
 Remove any headers not part of your platform.
*/
#include "string.h"
#include "stddef.h"
#include "stdlib.h"
#include "time.h"
#include "pthread.h"
#include "semaphore.h"
#include "errno.h"
#include "sys/types.h"
#include "sys/ioctl.h"
#include "unistd.h"
#include "sys/socket.h"
#include "sys/select.h"
#include "netinet/tcp.h"
#include "netinet/in.h"
#include "arpa/inet.h"
#include "fcntl.h"
#include "netdb.h"
#include "stdio.h"
#include "stdarg.h"
#include "ctype.h"
#include "sys/stat.h"
#include "dirent.h"
#include "limits.h"
#include "setjmp.h"
#include "stdint.h"
#include "math.h"
#include "sys/wait.h"
#include "assert.h"
#include "locale.h"
#include "float.h"
#include "dlfcn.h"
#include "termios.h"
#include "sys/time.h"
#include "signal.h"
#include "syslog.h"
